# Site settings
title: Starter Template for Jekyll
email: youremail@yourdomain.net
description: Built using Filament Group's Load CSS and Load JS and http://jch.penibelst.de/'s html compressor for optimising speed.
type: website
image: /assets/imgs/octojekyll.jpg
host: 0.0.0.0

# Server Config options
# livereload: true

# SASS
sass:
  sass_dir: assets/_sass
  style: compressed

team:
  - name: 김진형 
    img: /assets/imgs/team/pexels-photo-91227.jpeg
    position: CEO & Coach
    bio: "I'm not a real person. Well, I am but I'm not Bob Smith, CEO of this random site. This picture is from Pexel."
  - name: 박상욱
    img: /assets/imgs/team/pexels-photo-324658.jpeg
    position: Coach & Pysical Therapist
    bio: My bio is the longest. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.
  - name: 김병준
    img: /assets/imgs/team/pexels-photo-450271.jpeg
    position: Coach
    bio: Look at me smile hahahaha. I like to design pretty things or some other info about me and what I do at this company or startup.
